#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

if [ -x $HOME/scripts/mocitores.sh ];then
   sh $HOME/scripts/mocitores.sh
fi

feh --bg-fill /home/vertecedoc/Dotfiles/artworks/wallpapers/'descarga.jpeg' &
~/.config/polybar/launch.sh &
killall mate-notification-daemon; dunst & pamac-daemon &

bspc config pointer_modifier mod1
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           5
bspc config left_padding		10
bspc config right_padding		10

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config top_padding			 50
bspc config bottom_padding 		 20

bspc config pointer_action1     move

W=800
H=400
HH=700

screenwidth=$(xdpyinfo | awk -F’[ x]+’ ‘/dimensions:/{print $3}’) &
screenheight=$(xdpyinfo | awk -F’[ x]+’ ‘/dimensions:/{print $4}’) &
X=$((“$screenwidth”/2-“$windowwidth”/2)) &
Y=$((“$screenheight”/2-“$windowheight”/2)) &

bsspc rule -a Zathura state=foating rectangle="$W"x"$HH"+"$X"+"$Y"
bspc rule -a Gimp desktop='^4' state=floating follow=on rectangle="$W"x"$H"+"$X"+"$Y"
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Brave state=floating desktop='^2'
bspc rule -a Nautilus state=floating rectangle="$W"x"$H"+"$X"+"$Y"
alacritty &
dunst &
picom
