#! /bin/sh
#sh $HOME/scripts/lol.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

#if [[ $my_laptop_external_monitor = *connected* ]];then
#		 $HOME/scripts/mocitores.sh
#
#		 bspc monitor eDP1  -d 1 2 3 4 5 
#		 bspc monitor DP2  -d 6 7 8 9 10
#		 
#else
bspc monitor eDP1 -d Term Research Code Books School Office Video Noth Mail Notes Conf Spotifu 13
#fi

feh --bg-fill /home/vertecedoc/Wallpapers/ArchB.png &
~/.config/polybar/launch.sh &
 dunst & picom

#descoment for normal start
##bspc monitor eDP1  -d I II III IV V VI VII VIII IX X
#bspc monitor eDP1  -d 1 2 3 4 5 6 7 8 9 10

#DESCOMENT FOR DO THE SECOND MONITOR
#bspc monitor DP2  -d 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           3
bspc config left_padding		2
bspc config right_padding		2

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config top_padding			 22
bspc config bottom_padding 		 2


bsspc rule -a Zathura state=foating 
bspc rule -a Gimp desktop='^4' state=floating follow=on 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Brave state=floating 
bspc rule -a Nautilus state=floating 
bspc rule -a Alacritty state=tiling
bspc rule -a wine state=floating
bspc rule -a Inkscape state=floatinx
