#!/bin/bash

## Author : Aditya Shakya (adi1090x)
## Mail : adi1090x@gmail.com
## Github : @adi1090x
## Reddit : @adi1090x

rofi_command="rofi -m 0 -theme $HOME/.config/polybar/scripts/themes/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
poweroff=" Apagar"
reboot=" Reiniciar"
lock=" Bloquear"
suspend=" Hibernar"
logout=" Salir"

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$poweroff"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
        poweroff
        ;;
    $reboot)
        reboot
        ;;
    $lock)
        /home/vertecedoc/.config/polybar/scripts/lock.sh
        ;;
    $suspend)
        mpc -q pause
        amixer set Master mute
        systemctl suspend
        ;;
    $logout)
        bspc quit
        ;;
esac

