#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/usr/local/etc/X11/xinit/.Xresources
sysmodmap=/usr/local/etc/X11/xinit/.Xmodmap
LAST=/usr/local/etc/X11/xinit/last
DEFAULT_SESSION=$(cat /usr/local/etc/X11/xinit/pse)
DWM_SESSION=/home/vaer/.dwm/autostart

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if [[ -z "$DEFAULT_SESSION" ]]; then
		DEFAULT_SESSION=$DWM_SESSION
	fi




ars=''
get_session(){
	

	case $1 in

		awesome) ars='awesome' ;;
		qtile) ars='qtile start' ;;
		bspwm) ars='bspwm-session' ;;
		budgie) ars='budgie-desktop' ;;
		cinnamon) ars='cinnamon-session' ;;
		deepin) ars='startdde' ;;
		enlightenment) ars='enlightenment_start' ;;
		fluxbox) ars='startfluxbox' ;;
		gnome) ars='gnome-session' ;;
		i3|i3wm) ars='i3 --shmlog-size 0' ;;
		jwm) ars='jwm' ;;
		kde) ars='startplasma-x11' ;;
		lxde) ars='startlxde' ;;
		lxqt) ars='lxqt-session' ;;
		mate) ars='mate-session' ;;
		xfce) ars='xfce4-session' ;;
		openbox) ars='openbox-session' ;;
		default) ars=$DEFAULT_SESSION ;;
		*) ars=$1 ;;                      
	esac
	echo $ars
	echo $ars > /usr/local/etc/X11/xinit/pse
}
SESSION=$(get_session "$1")
if [[ "$SESSION" == "$DWM_SESSION" ]]; then
exec $(${SESSION}) 
else
/usr/local/libexec/polkit-gnome-authentication-agent-1 &
picom &
exec $SESSION     

fi








