#!/usr/bin/env bash

interval=0

cpuf() {

  printf "^c#3b414d^ ^b#7ec7a2^ CPU"
  printf "^c#abb2bf^ ^b#353b45^ $(cpu)"
}

update_icon() {
  printf "^c#7ec7a2^ "
}

pkg_updates() {
  updates=$(pkg audit | grep installed| awk '{print $4}') # void
  # updates=$(checkupdates | wc -l)   # arch , needs pacman contrib
  # updates=$(aptitude search '~U' | wc -l)  # apt (ubuntu,debian etc)

  if [ -z "$updates" ]; then
    printf "^c#7ec7a2^ No one package is vulnerable"
  else
    printf "^c#7ec7a2^ $updates"" package(s) are vulnerable"
  fi
}

# battery
batt() {
  printf "^c#81A1C1^  "
  printf "^c#81A1C1^ $(sysctl hw.acpi.battery.life | awk '{print $2}')"%% 
}

brightness() {


    backlight="$(intel_backlight | awk '{print $4}' | sed 's/%/%%/g')"

  printf "^c#BF616A^  $backlight"
}

mem() {
  printf "^c#7797b7^^b#1e222a^  "
  printf "^c#7797b7^ $(wcalc $(freecolor -m -o | head -n 2 | tail -n 1 | awk '{print $4}' )/1000 | awk '{print $2}')GiB"
}

#wlan() {
  #ssid=$( ifconfig | grep ssid | awk '{print $2}')
 # if [[ "$ssid" == "\"\"" ]]; then
#	printf "^c#3b414d^ ^b#7aa2f7^ 󰤭 ^d^%s" " ^c#7aa2f7^NW"
#  else
#        printf "^c#3b414d^ ^b#7aa2f7^ 󰤨 ^d^%s" " ^c#7aa2f7^C"
#  fi
#}

clock() {
  printf "^c#1e222a^ ^b#668ee3^ 󱑆 "
  printf "^c#1e222a^^b#7aa2f7^ $(date '+%a, %I:%M %p') "
}

while true; do

  [ $interval == 0 ] || [ $(($interval % 3600)) == 0 ] && updates=$(pkg_updates)
  interval=$((interval + 1))

  sleep 1 && xsetroot -name "$(update_icon) $updates $(batt) $(brightness) $(cpuf) $(mem) $(clock)"
done
